version: "3.5"

services:
    web:
        build:
            context: ./web
            target: 'develop-stage'
        ports:
            - 8080:8080
        volumes:
            - ./web:/app/web
            - /app/web/node_modules
        command: /bin/sh -c "npm run serve"

    api:
        build: ./api
        ports:
            - 8090:8090
        volumes:
            - ./api:/go/src/api
            
    pg:
        image: postgres:12.1
        ports:
            - 5432:5432
        volumes:
            - pg-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345

    pgadmin:
        image: dpage/pgadmin4:4.18
        ports:
            - 5050:80
        volumes:
            - /opt/docker/pgadmin:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: zafercelenk@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 12345

volumes:
    pg-data:
        driver: local
