version: "3.5"

services:
    web:
        build:
            context: ./web
            target: 'develop-stage'
        ports:
            - 8080:8080
        volumes:
            - ./web:/app/web
            - /app/web/node_modules
        command: /bin/sh -c "npm run serve"

    api:
        build: ./api
        ports:
            - 8090:8090
        volumes:
            - ./api:/go/src/api
